<a href="https://colab.research.google.com/github/BhumiRaval123/Machine-Learning/blob/main/CLUSTERING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [3]:
from google.colab import drive

In [4]:
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
cd /content/drive/"My Drive/Colab Notebooks"

/content/drive/My Drive/Colab Notebooks


In [6]:
dataset = pd.read_csv("StudentsPerformance.csv")
print(dataset)
dataset.shape

     gender race/ethnicity  ... reading score writing score
0    female        group B  ...            72            74
1    female        group C  ...            90            88
2    female        group B  ...            95            93
3      male        group A  ...            57            44
4      male        group C  ...            78            75
..      ...            ...  ...           ...           ...
995  female        group E  ...            99            95
996    male        group C  ...            55            55
997  female        group C  ...            71            65
998  female        group D  ...            78            77
999  female        group D  ...            86            86

[1000 rows x 8 columns]


(1000, 8)

In [7]:
dataset.describe()

math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [32]:
dataset=pd.get_dummies(dataset)
dataset.head(5)
 


math score  ...  test preparation course_none
0          72  ...                             1
1          69  ...                             0
2          90  ...                             1
3          47  ...                             1
4          76  ...                             1

[5 rows x 20 columns]

In [ ]:
dataset.shape

In [25]:
x = dataset.drop(columns=['math score'])
y = dataset['math score']

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state=100) 

In [28]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()
scaler = scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [29]:
from sklearn.neighbors import KNeighborsClassifier

knc = KNeighborsClassifier(6, p=6)

In [30]:
knc.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=6,
                     weights='uniform')

In [31]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score
print(classification_report(y_test, knc.predict(X_test)))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         0
          23       0.00      0.00      0.00         0
          26       0.00      0.00      0.00         0
          27       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         0
          30       0.00      0.00      0.00         0
          32       0.00      0.00      0.00         0
          34       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         0
          36       0.00      0.00      0.00         1
          37       0.00      0.00      0.00         1
          38       0.00      0.00      0.00         0
          39       0.00      0.00      0.00         2
          40       0.00      0.00      0.00         0
          41       0.00      0.00      0.00         3
          42       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
print(confusion_matrix(y_test, knc.predict(X_test)))

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
